name: Build Faiss Libraries

on:
  workflow_dispatch:
    inputs:
      faiss_version:
        description: 'Faiss version to build (e.g., v1.11.0)'
        required: true
        default: 'v1.11.0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
            name: darwin-arm64
          - os: ubuntu-latest
            arch: amd64
            name: linux-amd64
          - os: ubuntu-latest
            arch: arm64
            name: linux-arm64
          - os: windows-latest
            arch: amd64
            name: windows-amd64

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #---------------------------------------------------
    # Step 1: Set up build environment
    #---------------------------------------------------
    - name: Set up build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libopenblas-dev

    - name: Set up build environment (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install libomp openblas

    #---------------------------------------------------
    # Step 2: Build Faiss
    #---------------------------------------------------
    - name: Set up and Build Faiss (Linux arm64)
      if: matrix.name == 'linux-arm64'
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        run: |
          apt-get update
          apt-get install -y build-essential libopenblas-dev git cmake
          git clone https://github.com/facebookresearch/faiss.git
          cd faiss
          git checkout ${{ inputs.faiss_version }}
          cmake . -B build \
            -DFAISS_ENABLE_GPU=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DFAISS_ENABLE_PYTHON=OFF \
            -DBUILD_TESTING=OFF \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 2
          cmake --install build --prefix dist

    - name: Build Faiss (macOS)
      if: matrix.name == 'darwin-arm64'
      shell: bash
      run: |
        git clone https://github.com/facebookresearch/faiss.git
        cd faiss
        git checkout ${{ inputs.faiss_version }}
        cmake . -B build \
          -DOpenMP_ROOT=$(brew --prefix libomp) \
          -DFAISS_ENABLE_GPU=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -DFAISS_ENABLE_PYTHON=OFF \
          -DBUILD_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -j 2
        cmake --install build --prefix dist

    - name: Build Faiss (Linux amd64)
      if: matrix.name == 'linux-amd64'
      shell: bash
      run: |
        git clone https://github.com/facebookresearch/faiss.git
        cd faiss
        git checkout ${{ inputs.faiss_version }}
        cmake . -B build \
          -DFAISS_ENABLE_GPU=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -DFAISS_ENABLE_PYTHON=OFF \
          -DBUILD_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -j 2
        cmake --install build --prefix dist

    - name: Build Faiss (Windows amd64)
      if: matrix.name == 'windows-amd64'
      shell: pwsh
      run: |
        # Install OpenBLAS using vcpkg
        Write-Host "Setting up vcpkg..."
        $VCPKG_ROOT = "D:/vcpkg"
        git clone https://github.com/Microsoft/vcpkg.git $VCPKG_ROOT
        & "$VCPKG_ROOT/bootstrap-vcpkg.bat"
        Write-Host "Installing OpenBLAS via vcpkg..."
        & "$VCPKG_ROOT/vcpkg" install openblas:x64-windows --recurse
        
        # Set the CMAKE_TOOLCHAIN_FILE environment variable for subsequent steps
        $env:CMAKE_TOOLCHAIN_FILE = "$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        Write-Host "CMAKE_TOOLCHAIN_FILE environment variable set to: $env:CMAKE_TOOLCHAIN_FILE"

        Write-Host "Cloning Faiss..."
        git clone https://github.com/facebookresearch/faiss.git
        cd faiss
        git checkout ${{ inputs.faiss_version }}
        
        Write-Host "Configuring Faiss with CMake..."
        # CMake will automatically use the CMAKE_TOOLCHAIN_FILE environment variable
        cmake . -B build `
          -DFAISS_ENABLE_GPU=OFF `
          -DBUILD_SHARED_LIBS=ON `
          -DFAISS_ENABLE_PYTHON=OFF `
          -DBUILD_TESTING=OFF `
          -DCMAKE_BUILD_TYPE=Release
        
        Write-Host "Building Faiss..."
        cmake --build build --config Release -j 2
        Write-Host "Installing Faiss..."
        cmake --install build --prefix dist

    #---------------------------------------------------
    # Step 3: Prepare Artifacts
    #---------------------------------------------------
    - name: Prepare Artifacts for Upload
      run: |
        # Create the directory structure for the artifact
        mkdir -p artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}
        
        # Define source path based on OS and architecture
        SOURCE_PATH="faiss/dist"
        
        # Copy library files
        if [[ "${{ runner.os }}" == "Linux" || "${{ runner.os }}" == "macOS" ]]; then
          cp $SOURCE_PATH/lib/libfaiss.so* artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/ 2>/dev/null || true
          cp $SOURCE_PATH/lib/libfaiss_c.so* artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/ 2>/dev/null || true
          cp $SOURCE_PATH/lib/libfaiss.dylib* artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/ 2>/dev/null || true
          cp $SOURCE_PATH/lib/libfaiss_c.dylib* artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/ 2>/dev/null || true
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          cp $SOURCE_PATH/bin/faiss.dll artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/
          cp $SOURCE_PATH/bin/faiss_c.dll artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/
          # Also copy the .lib file needed for linking on Windows
          cp $SOURCE_PATH/lib/faiss.lib artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/
          cp $SOURCE_PATH/lib/faiss_c.lib artifact/faisslib/${{ inputs.faiss_version }}/${{ matrix.name }}/
        fi
      shell: bash

    #---------------------------------------------------
    # Step 4: Upload Artifact
    #---------------------------------------------------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: faiss-libs-${{ matrix.name }}
        path: artifact/ 